### ISSUE TITLE
Remove Data

### ISSUE THREAD

**Issue by peterfoxflick** [Mando75/CS450#1]
Hi Bryan, 

Could you remove the data from the JSON folder.

Peter

**Comment by Mando75** [comment]
Absolutely. I forgot I had added them when I made this repo public. I will purge them from the file history and make it public again. Good catch!

**Comment by Mando75** [comment]
Data is removed and all the file history has been purged from the git repo. I checked, and the files were in the gitignore, so idk how they got added. Everything should be gucci now tho
